version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_CONTENT_PAT }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - quantco/ci
    registries:
      - github
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /template/.github/workflows
    schedule:
      interval: daily
    reviewers:
      - quantco/ci
    registries:
      - github
    groups:
      dependencies:
        patterns:
          - "*"
