name: pre-commit-conda
description: run pre-commit
inputs:
  extra-args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  condarc-file:
    description: path to a custom condarc file
    required: false
    default: ''
  python-version:
    description: python version to use
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
  - name: Set up micromamba
    uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
    with:
      condarc-file: ${{ inputs.condarc-file }}
      environment-name: pre-commit
      cache-environment-key: pre-commit-3|${{ inputs.python-version }}
      create-args: >-
        python=${{ inputs.python-version }}
        pre-commit=3
  - name: Cache pre-commit
    uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ inputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - name: Run pre-commit
    run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra-args }}
    env:
      PRE_COMMIT_USE_MICROMAMBA: '1'
    shell: bash -el {0}
