name: pre-commit-conda
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  condarc_file:
    description: path to a custom condarc file
    required: false
    default: ''
  python_version:
    description: python version to use
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
  - name: Set up micromamba
    uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
    with:
      condarc_file: ${{ inputs.condarc_file }}
      environment-name: pre-commit
      cache-environment-key: pre-commit-3|${{ inputs.python_version }}
      create-args: >-
        python=${{ inputs.python_version }}
        pre-commit=3
  - name: Cache pre-commit
    uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ inputs.python_version }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - name: Run pre-commit
    run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    env:
      PRE_COMMIT_USE_MICROMAMBA: '1'
    shell: bash -el {0}
