name: Bump versions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * MON"

jobs:
  bump:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { tool: mamba-org/setup-micromamba }
          - { tool: actions/cache }
    name: Bump ${{ matrix.tool }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump versions
        id: bump
        run: |
          set -euo pipefail
          new_version="$(gh repo view --json latestRelease ${{ matrix.tool }} | jq -r '.latestRelease.tagName')"
          echo "new-version=$new_version" >> "$GITHUB_OUTPUT"
          commit_sha="$(gh api "repos/${{ matrix.tool }}/commits/$new_version" | jq -r '.sha')"
          current_sha="$(grep "${{ matrix.tool }}@" action.yml | awk -F@ '{print $2}')"
          if [[ "$commit_sha" != "$current_sha" ]]; then
            sed -i "s/${{ matrix.tool }}@${current_sha}/${{ matrix.tool }}@${commit_sha}/g" action.yml
          else
            echo "${{ matrix.tool }} is already at the latest version: $current_sha"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          title: Bump ${{ matrix.tool }} to ${{ steps.bump.outputs.new-version }}
          delete-branch: true
          commit-message: Bump ${{ matrix.tool }} version to ${{ steps.bump.outputs.new-version }}
          branch: bump-${{ matrix.tool }}-${{ steps.bump.outputs.new-version }}
