name: Release

on:
  push:
    tags:
      # only release von 'vx.y.z' tags, not on the 'vx' tag itself
      - 'v*.*.*'
permissions:
  contents: write

# To release a new version, create a release called `v*.*.*` from the GitHub UI.
# This will create a draft release with the changelog and push a 'vx' tag that points to the new release.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/release.sh
        env:
          TAG_NAME: ${{ github.ref_name }}
